import { ARTICLES } from "../lib/articles";

const BASE = "https://zemitest.com";

export default function sitemap() {
  const staticPages = [
  "",
  "/tests",
  "/articles",
  "/about",
  "/privacy",
  "/contact",
  "/tests/lifesim",
  "/tests/moral",
  "/tests/legacy",
  "/tests/karma",
  "/tests/stock",
  "/tests/princess",
  "/tests/youtube",
  "/tests/human",
  "/tests/social",
  "/tests/liar",
  "/tests/nunchi",
  "/tests/difficulty",
  "/tests/island",
  "/tests/animal",
  "/tests/career",
  "/tests/spending",
  "/tests/love",
  "/tests/pastlife",
  "/tests/stress",
  "/tests/money",
  "/tests/politics",
  "/tests/lifesim/types",
  "/tests/moral/types",
  "/tests/legacy/types",
  "/tests/karma/types",
  "/tests/stock/types",
  "/tests/princess/types",
  "/tests/youtube/types",
  "/tests/human/types",
  "/tests/social/types",
  "/tests/liar/types",
  "/tests/nunchi/types",
  "/tests/difficulty/types",
  "/tests/island/types",
  "/tests/animal/types",
  "/tests/career/types",
  "/tests/spending/types",
  "/tests/love/types",
  "/tests/pastlife/types",
  "/tests/stress/types",
  "/tests/money/types",
  "/tests/politics/types",
];
  return [
    ...staticPages.map((path) => ({
      url: `${BASE}${path}`,
      lastModified: new Date(),
    })),
    ...ARTICLES.map((a) => ({
      url: `${BASE}/articles/${a.slug}`,
      lastModified: new Date(a.date),
    })),
  ];
}
