// 테스트 목록. 새 테스트 만들면 여기에 한 줄 추가하면 홈에 자동으로 뜸.
// ready: false 로 두면 "COMING SOON" 으로 표시됨.

export const TESTS = [
  {
    slug: "youtube",
    grad: ["#ff6b6b", "#ff9a5c"],
    category: "score",
    emoji: "📺",
    title: "당신이 유튜버라면 예상 구독자는?",
    desc: "예상 구독자 수와 실버·골드·다이아 버튼 등급, 어울리는 채널 유형까지.",
    meta: "20문항 · 예상 구독자 수",
    href: "/tests/youtube",
    ready: true,
  },
  {
    slug: "lifesim",
    grad: ["#ffd76f", "#f7913a"],
    category: "sim",
    emoji: "🎲",
    title: "인생 시뮬레이션",
    desc: "몸이나 돈이 바닥나면 예고 없이 끝납니다. 3,700가지 경로, 28가지 결말.",
    meta: "28~36장면 · 엔딩 25종",
    href: "/tests/lifesim",
    ready: true,
  },
  {
    slug: "moral",
    grad: ["#ffb0d8", "#c9455e"],
    category: "value",
    emoji: "⚖️",
    title: "너라면 누구를 살릴래?",
    desc: "기차, 침몰하는 배, 불타는 건물. 20번의 선택이 당신을 말해줍니다.",
    meta: "20문항 · 결과 6종",
    href: "/tests/moral",
    ready: true,
  },
  {
    slug: "legacy",
    grad: ["#a18cd1", "#fbc2eb"],
    category: "psych",
    emoji: "🕊️",
    title: "죽기 직전 어떤 사람으로 기억될까?",
    desc: "당신의 묘비에 새겨질 한 문장. 사람들은 당신을 어떻게 기억할까요?",
    meta: "22문항 · 결과 8종",
    href: "/tests/legacy",
    ready: true,
  },
  {
    slug: "social",
    grad: ["#ff9a9e", "#ff6b9d"],
    category: "score",
    emoji: "🎖️",
    title: "사회생활 생존력",
    desc: "거절, 실수 대응, 부당한 요구까지. 조직에서 나를 지키는 처세력은?",
    meta: "20문항 · 상위 % 공개",
    href: "/tests/social",
    ready: true,
  },
  {
    slug: "liar",
    grad: ["#4facfe", "#5b86e5"],
    category: "score",
    emoji: "🔍",
    title: "거짓말 탐지력 테스트",
    desc: "이 사람 거짓말일까 진실일까? 사람 평균 정확도는 54%입니다.",
    meta: "20문항 · 정확도 · 상위 %",
    href: "/tests/liar",
    ready: true,
  },
  {
    slug: "human",
    grad: ["#ffd76f", "#fc7d4c"],
    category: "score",
    emoji: "👑",
    title: "너는 상위 몇 프로의 인간인가?",
    desc: "멘탈·사회성·자기관리·판단력·체력·공감력. 6개 영역 종합 능력치.",
    meta: "24문항 · 6개 영역 · 상위 %",
    href: "/tests/human",
    ready: true,
  },
  {
    slug: "nunchi",
    grad: ["#5f67cc", "#855bb0"],
    category: "score",
    emoji: "👀",
    title: "눈치 테스트",
    desc: "20가지 상황에서 가장 적절한 행동은? 실제 참여자 기준 상위 %까지.",
    meta: "20문항 · 상위 % 공개",
    href: "/tests/nunchi",
    ready: true,
  },
  {
    slug: "difficulty",
    grad: ["#84fab0", "#4e8f2e"],
    category: "score",
    emoji: "🎮",
    title: "너의 인생 난이도는?",
    desc: "일상의 귀찮음을 게임 난이도로. EASY부터 NIGHTMARE까지.",
    meta: "20문항 · 난이도 5단계",
    href: "/tests/difficulty",
    ready: true,
  },
  {
    slug: "island",
    grad: ["#43cea2", "#185a9d"],
    category: "score",
    emoji: "🏝️",
    title: "무인도 생존력 테스트",
    desc: "물, 불, 식량, 구조 신호까지. 나는 무인도에서 며칠 버틸까?",
    meta: "20문항 · 생존 일수",
    href: "/tests/island",
    ready: true,
  },
  {
    slug: "love",
    grad: ["#ff8a5c", "#ff5f8d"],
    category: "psych",
    emoji: "💘",
    title: "나의 연애 세계관 테스트",
    desc: "20개의 질문으로 알아보는 나의 연애 유형. 유형별 퍼센트까지 확인해보세요.",
    meta: "20문항 · 결과 6종",
    href: "/tests/love",
    ready: true,
  },
  {
    slug: "pastlife",
    grad: ["#b06ab3", "#4568dc"],
    category: "psych",
    emoji: "🔮",
    title: "전생에 나는 뭐였을까",
    desc: "20개의 질문으로 찾아가는 나의 전생. 12가지 인물 중 나는 누구였을까?",
    meta: "20문항 · 결과 12종",
    href: "/tests/pastlife",
    ready: true,
  },
  {
    slug: "animal",
    grad: ["#84fab0", "#8fd3f4"],
    category: "psych",
    emoji: "🐾",
    title: "나와 닮은 동물은?",
    desc: "22개의 질문으로 찾는 나의 동물. 16가지 중 나는 누구를 닮았을까?",
    meta: "22문항 · 결과 16종",
    href: "/tests/animal",
    ready: true,
  },
  {
    slug: "stress",
    grad: ["#7fc649", "#4e8f2e"],
    category: "psych",
    emoji: "🌿",
    title: "스트레스 유형과 힐링 처방",
    desc: "스트레스에 반응하는 8가지 방식과, 나에게 맞는 회복법을 알려드립니다.",
    meta: "24문항 · 결과 8종",
    href: "/tests/stress",
    ready: true,
  },
  {
    slug: "politics",
    grad: ["#8fd3f4", "#4facfe"],
    category: "value",
    emoji: "🗳️",
    title: "정치 성향 좌표 테스트",
    desc: "경제와 사회, 두 개의 축으로 나의 정치 성향 좌표를 찍어봅니다.",
    meta: "20문항 · 결과 5종",
    href: "/tests/politics",
    ready: true,
  },
  {
    slug: "career",
    grad: ["#5f67cc", "#3b58bb"],
    category: "value",
    emoji: "🧭",
    title: "직업 가치관 테스트",
    desc: "일에서 무엇을 가장 중요하게 여기는지 알아봅니다. 8가지 가치관 중 나는?",
    meta: "24문항 · 결과 8종",
    href: "/tests/career",
    ready: true,
  },
  {
    slug: "spending",
    grad: ["#ffb3d9", "#c9a5ff"],
    category: "value",
    emoji: "🛍️",
    title: "소비 성향 테스트",
    desc: "돈을 쓰는 방식으로 알아보는 나의 소비 유형과 맞춤 관리법.",
    meta: "22문항 · 결과 8종",
    href: "/tests/spending",
    ready: true,
  },
  {
    slug: "money",
    grad: ["#f7b733", "#fc7d4c"],
    category: "value",
    emoji: "💰",
    title: "나의 경제력 테스트",
    desc: "저축, 소비 관리, 금융 이해, 위험 대비. 4개 영역을 점수로 확인합니다.",
    meta: "24문항 · 상위 % 공개",
    href: "/tests/money",
    ready: true,
  },
];
