// 테스트 목록. 새 테스트 만들면 여기에 한 줄 추가하면 홈에 자동으로 뜸.
// ready: false 로 두면 "COMING SOON" 으로 표시됨.

export const TESTS = [
  {
    slug: "love",
    category: "psych",
    emoji: "💘",
    title: "나의 연애 세계관 테스트",
    desc: "20개의 질문으로 알아보는 나의 연애 유형. 유형별 퍼센트까지 확인해보세요.",
    meta: "20문항 · 결과 6종",
    href: "/tests/love",
    ready: true,
  },
  {
    slug: "pastlife",
    category: "psych",
    emoji: "🔮",
    title: "전생에 나는 뭐였을까",
    desc: "28개의 질문으로 찾아가는 나의 전생. 12가지 인물 중 나는 누구였을까?",
    meta: "28문항 · 결과 12종",
    href: "/tests/pastlife",
    ready: true,
  },
  {
    slug: "animal",
    category: "psych",
    emoji: "🐾",
    title: "나와 닮은 동물은?",
    desc: "27개의 질문으로 찾는 나의 동물. 16가지 중 나는 누구를 닮았을까?",
    meta: "27문항 · 결과 16종",
    href: "/tests/animal",
    ready: true,
  },
  {
    slug: "stress",
    category: "psych",
    emoji: "🌿",
    title: "스트레스 유형과 힐링 처방",
    desc: "스트레스에 반응하는 8가지 방식과, 나에게 맞는 회복법을 알려드립니다.",
    meta: "24문항 · 결과 8종",
    href: "/tests/stress",
    ready: true,
  },
  {
    slug: "politics",
    category: "value",
    emoji: "🗳️",
    title: "정치 성향 좌표 테스트",
    desc: "경제와 사회, 두 개의 축으로 나의 정치 성향 좌표를 찍어봅니다.",
    meta: "30문항 · 결과 5종",
    href: "/tests/politics",
    ready: true,
  },
  {
    slug: "career",
    category: "value",
    emoji: "🧭",
    title: "직업 가치관 테스트",
    desc: "일에서 무엇을 가장 중요하게 여기는지 알아봅니다. 8가지 가치관 중 나는?",
    meta: "24문항 · 결과 8종",
    href: "/tests/career",
    ready: true,
  },
  {
    slug: "spending",
    category: "value",
    emoji: "🛍️",
    title: "소비 성향 테스트",
    desc: "돈을 쓰는 방식으로 알아보는 나의 소비 유형과 맞춤 관리법.",
    meta: "22문항 · 결과 8종",
    href: "/tests/spending",
    ready: true,
  },
  {
    slug: "money",
    category: "value",
    emoji: "💰",
    title: "나의 경제력 테스트",
    desc: "저축, 소비 관리, 금융 이해, 위험 대비. 4개 영역을 점수로 확인합니다.",
    meta: "24문항 · 100점 만점",
    href: "/tests/money",
    ready: true,
  },
];
